// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDILccmIGL9CsOabaSz5VcKUuCqOKgYlKg',
    appId: '1:448290544287:web:ec7434f28d519fcdc220aa',
    messagingSenderId: '448290544287',
    projectId: 'dripnotes-e5756',
    authDomain: 'dripnotes-e5756.firebaseapp.com',
    storageBucket: 'dripnotes-e5756.firebasestorage.app',
    measurementId: 'G-GFWGYZFVBR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjWCf5RETuVKMGxjjod6dQb8J5gXW5OO0',
    appId: '1:448290544287:ios:c552859577eec30cc220aa',
    messagingSenderId: '448290544287',
    projectId: 'dripnotes-e5756',
    storageBucket: 'dripnotes-e5756.firebasestorage.app',
    iosBundleId: 'shop.drippingmonks.dripnotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDILccmIGL9CsOabaSz5VcKUuCqOKgYlKg',
    appId: '1:448290544287:web:dbf7d21970f7c4fcc220aa',
    messagingSenderId: '448290544287',
    projectId: 'dripnotes-e5756',
    authDomain: 'dripnotes-e5756.firebaseapp.com',
    storageBucket: 'dripnotes-e5756.firebasestorage.app',
    measurementId: 'G-G05TE3ES01',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfKRWWkReqJwWYjtQh6t2P-KikxICXxM',
    appId: '1:498964911275:ios:34a3826c094a2694bbd3ee',
    messagingSenderId: '498964911275',
    projectId: 'dripnotes-new-2025',
    storageBucket: 'dripnotes-new-2025.firebasestorage.app',
    iosBundleId: 'shop.drippingmonks.dripnotes',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3bwu7OCq9SKkLl6AwksYd31eUWQmbhO4',
    appId: '1:498964911275:android:a12fc07556b6e2a6bbd3ee',
    messagingSenderId: '498964911275',
    projectId: 'dripnotes-new-2025',
    storageBucket: 'dripnotes-new-2025.firebasestorage.app',
  );

}